-- how to rename column
-- Alter table `E1.employees`
-- rename column string_field_1 to Name ;

-- Alter table `E1.employees`
-- rename column string_field_2 to Department;

--delete column  this is paid feature s
-- delete from `E1.employees`
-- where EmployeID = 'EmployeID';



-- star select all the columns
select *  
from `E1.customers`
limit 5; -- limit 5 tell about top 5 rows 

-- Show thr name of thr customers 

select Name
from `E1.customers`;

-- show customer cities
select City
from `E1.customers`
limit 10;

-- Finane wants only payment methods
select *
from `E1.payments`
limit 10;

select Method
from `E1.payments`;

-- hr wants name of the 
select*
from `E1.employees`
limit 5;

select Name
from `E1.employees`
limit 5;

select * 
from `E1.products`
limit10;

select 
 ProductID,
  ProductName
from `E1.products`;

select 
  ProductID,
  ProductName,
  CategoryID
from `E1.products`
limit 10 ;

select sellingprice
from `E1.products`;

select city
from `E1.customers`;


select distinct city 
from `E1.customers`;

-- Different payment methods 
select distinct method
from `E1.payments`;


select *
from `E1.suppliers`;
--  the customers support team wanta a list of all customers with their city
select CustomerID , City
from `E1.customers`;

select* from `E1.products` limit 5;
select distinct categoryId
from `E1.products`;

select *
from `E1.customers`
where age >= 30;

select* 
from `E1.products`
where SellingPrice <= 50000;

select*
from `E1.orders`
where status != 'Delivered';

select distinct Status
from `E1.orders`;

select count(*) -- star count the total number of rows 
from `E1.customers`;


--Count total customers from mumbai
select count(*)
from `E1.customers`
where city = 'Mumbai';

select*
from `E1.employees`
where Department = 'Operations';

select*
from `E1.products`
where SupplierID = 'SUP003';

select *
from `E1.inventory`;

select ProductID
from `E1.inventory`
where Stock < 30 ;

select *
from `E1.customers`
where SignupDate > '2026-01-01';

-- different product categories exits in the product table

select count(distinct CategoryID)
from `E1.products`;

 -- different cities the customers belong to 
select distinct city
from `E1.customers`;

select count(distinct city)
from `E1.customers`;

--  how many different products do we have 

select count(*)
from `E1.products` ;

select count(*)
from `E1.customers` 
where city = 'Mumbai';

select count(*) -- count the star calculate the number of rows 
from `E1.customers`;

-- count(column) counts the number of non-null values in that column 
select count(CustomerID)
from `E1.customers`;

 -- how manh different supplier states exit
select distinct state 
from  `E1.suppliers`;

select count (distinct state )
from  `E1.suppliers`;

-- total sales value 
select *
from `E1.order_items`
limit 5;

select sum (Total) -- total means --> quantity * selling price = total 
from `E1.order_items`;

select sum(Quantity)
from `E1.order_items`;

select sum(Quantity)
from `E1.order_items`
where Quantity > 1 ;

-- the avg selling price of the products;

select *
from `E1.products`
limit 5;

select avg(SellingPrice)
from `E1.products`;

-- give name avg selling price
select avg(SellingPrice) as Avg_Selling_Price
from `E1.products`;

-- Summary of all payments transactions

select Status,
from `E1.payments`
limit 5;

select
  count(*) as No_Of_Payments,
  sum (amount) as Total_payment_amt,
  avg(amount) as avg_payment,
  min(amount) as min_payment,
  max(amount) as max_payment
from `E1.payments`;

-- *the count of the number of products within each  category
select *
from `E1.products`;

-- *group by , create grops , if can see for each than use group by 

select CategoryID, 
  count(*) as product_cnt
  from `E1.products`
  group by CategoryID;

-- units of each product have been sold?

select 
  sum(Quantity) as total_qty
  from `E1.order_items`
  group by ProductID;

select 
  ProductID,
  sum(Quantity) as total_qty
  from `E1.order_items`
  group by ProductID;

-- total sales value generated by each products

select *
  from `E1.order_items`
  limit 5;

select  ProductID,
  sum(Total) as total_sales
  from `E1.order_items`
  group by ProductID ; 

-- avg selling price at which each product was sold
select ProductID,
  avg(SellingPrice) as Avg_sp
  from `E1.order_items`
  group by ProductID;

-- products sales summary --> for every product , what is the statics summary
select ProductID,
  count(*) as totat_orders,
  sum(total) as total_sales,
  max(total) as max_sales,
  min(total) as minn_sales,
  round (avg(total),2) as avg_sales
from `E1.order_items`
group by ProductID;

-- for eacch customer, how many orders are there for each of their different order items 

select*
  from `E1.orders`
  limit 5;

select
  CustomerID ,
  Status,
  count(*) as totao_order_per_customer 
  from `E1.orders`
  group by Status, CustomerID;

-- different products are there overall

select *
from `E1.products`
limit 5;

select count(*)
from `E1.products`;

--how many products are there in each category

select CategoryID, 
 count(*) as totao_count,
 from `E1.products`
 group by CategoryID;

-- hw many unites of each products have been sold
select *
from `E1.order_items`
limit 5;

select 
ProductID,
SellingPrice, -- extra addition in ques
sum(Quantity) as total_qty,
sum(total) as total_price
from `E1.order_items`
group by ProductID, SellingPrice;

-- total sales value generated byy each product

select
ProductID,
sum(total) as total_sales
from `E1.order_items`
group by ProductID;


-- the lowest and highest selling price recorded for each products

select *
from `E1.order_items`
limit 5;

select
ProductID,
min(SellingPrice) as lowest_sp,
max(SellingPrice) as highest_sp
from `E1.order_items`
group by ProductID


-- for each of the order status , what is the number of orders for each of the customer

select
CustomerID, 
Status,
count(*) as total_count
from `E1.orders`
group by CustomerID, Status;

-- Inventory records are maintained for each warehouse 

select *
from `E1.inventory`
limit 5;

select
WarehouseID,
count(stock)  as recods 
from `E1.inventory`
group by WarehouseID;


-- how many orders handled by each of the employes for each status;

select *
from `E1.orders`
limit 5; 

select
  EmployeeID,
  Status,
count(*) as total_orders 
from `E1.orders`
group by EmployeeID, Status;


-- how many products in each category have MRP > rs-20,000

select *
from `E1.product


select 
 CategoryID,
 count(*) as total_products,
from `E1.products`
where MRP > 20000
group by CategoryID


